# Generated by Django 5.1.5 on 2025-01-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formsdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='信息编号')),
                ('feedback_date', models.DateField(verbose_name='反馈日期')),
                ('feedback_department', models.CharField(max_length=30, verbose_name='反馈部门')),
                ('title', models.CharField(max_length=30, verbose_name='报告题目')),
                ('author', models.CharField(max_length=30, verbose_name='作者')),
                ('unit', models.CharField(max_length=30, verbose_name='所在单位')),
                ('accept_level', models.CharField(max_length=30, verbose_name='采纳级别')),
                ('instruction_level', models.CharField(max_length=30, verbose_name='批示级别')),
                ('remark', models.CharField(max_length=30, verbose_name='备注')),
            ],
        ),
    ]
