# Generated by Django 5.1.6 on 2025-02-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_formsdata_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsdata',
            name='author_2',
            field=models.CharField(default='', max_length=30, verbose_name='作者2'),
        ),
        migrations.AddField(
            model_name='formsdata',
            name='author_3',
            field=models.CharField(default='', max_length=30, verbose_name='作者3'),
        ),
        migrations.AddField(
            model_name='formsdata',
            name='unit_2',
            field=models.CharField(default='', max_length=30, verbose_name='作者2所在单位'),
        ),
        migrations.AddField(
            model_name='formsdata',
            name='unit_3',
            field=models.CharField(default='', max_length=30, verbose_name='作者3所在单位'),
        ),
        migrations.AlterField(
            model_name='formsdata',
            name='author',
            field=models.CharField(max_length=30, verbose_name='作者1'),
        ),
        migrations.AlterField(
            model_name='formsdata',
            name='title',
            field=models.CharField(max_length=50, verbose_name='报告题目'),
        ),
        migrations.AlterField(
            model_name='formsdata',
            name='unit',
            field=models.CharField(max_length=30, verbose_name='作者1所在单位'),
        ),
    ]
