# Generated by Django 5.1.6 on 2025-03-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_formsdata_author_2_formsdata_author_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsdata',
            name='author_4',
            field=models.CharField(default='', max_length=50, verbose_name='作者四'),
        ),
        migrations.AddField(
            model_name='formsdata',
            name='author_5',
            field=models.CharField(default='', max_length=50, verbose_name='作者五'),
        ),
        migrations.AddField(
            model_name='formsdata',
            name='unit_4',
            field=models.CharField(default='', max_length=50, verbose_name='作者四所在单位'),
        ),
        migrations.AddField(
            model_name='formsdata',
            name='unit_5',
            field=models.CharField(default='', max_length=50, verbose_name='作者五所在单位'),
        ),
        migrations.AlterField(
            model_name='formsdata',
            name='accept_level',
            field=models.CharField(default='', max_length=50, verbose_name='采纳级别'),
        ),
        migrations.AlterField(
            model_name='formsdata',
            name='author',
            field=models.CharField(default='', max_length=50, verbose_name='作者一'),
        ),
        migrations.AlterField(
            model_name='formsdata',
            name='author_2',
            field=models.CharField(default='', max_length=50, verbose_name='作者二'),
        ),
        migrations.AlterField(
            model_name='formsdata',
            name='author_3',
            field=models.CharField(default='', max_length=50, verbose_name='作者三'),
        ),
        migrations.AlterField(
            model_name='formsdata',
            name='feedback_department',
            field=models.CharField(default='', max_length=50, verbose_name='反馈部门'),
        ),
        migrations.AlterField(
            model_name='formsdata',
            name='instruction_level',
            field=models.CharField(default='', max_length=50, verbose_name='批示级别'),
        ),
        migrations.AlterField(
            model_name='formsdata',
            name='number',
            field=models.CharField(default='', max_length=50, verbose_name='信息编号'),
        ),
        migrations.AlterField(
            model_name='formsdata',
            name='remark',
            field=models.CharField(default='', max_length=100, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='formsdata',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='报告题目'),
        ),
        migrations.AlterField(
            model_name='formsdata',
            name='unit',
            field=models.CharField(default='', max_length=50, verbose_name='作者一所在单位'),
        ),
        migrations.AlterField(
            model_name='formsdata',
            name='unit_2',
            field=models.CharField(default='', max_length=50, verbose_name='作者二所在单位'),
        ),
        migrations.AlterField(
            model_name='formsdata',
            name='unit_3',
            field=models.CharField(default='', max_length=50, verbose_name='作者三所在单位'),
        ),
    ]
