# Generated by Django 5.1.6 on 2025-03-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_alter_formsdata_accept_level_alter_formsdata_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsdata',
            name='author_10',
            field=models.CharField(default='', max_length=255, verbose_name='作者十'),
        ),
        migrations.AddField(
            model_name='formsdata',
            name='author_6',
            field=models.CharField(default='', max_length=255, verbose_name='作者六'),
        ),
        migrations.AddField(
            model_name='formsdata',
            name='author_7',
            field=models.CharField(default='', max_length=255, verbose_name='作者七'),
        ),
        migrations.AddField(
            model_name='formsdata',
            name='author_8',
            field=models.CharField(default='', max_length=255, verbose_name='作者八'),
        ),
        migrations.AddField(
            model_name='formsdata',
            name='author_9',
            field=models.CharField(default='', max_length=255, verbose_name='作者九'),
        ),
        migrations.AddField(
            model_name='formsdata',
            name='unit_10',
            field=models.CharField(default='', max_length=255, verbose_name='作者十所在单位'),
        ),
        migrations.AddField(
            model_name='formsdata',
            name='unit_6',
            field=models.CharField(default='', max_length=255, verbose_name='作者六所在单位'),
        ),
        migrations.AddField(
            model_name='formsdata',
            name='unit_7',
            field=models.CharField(default='', max_length=255, verbose_name='作者七所在单位'),
        ),
        migrations.AddField(
            model_name='formsdata',
            name='unit_8',
            field=models.CharField(default='', max_length=255, verbose_name='作者八所在单位'),
        ),
        migrations.AddField(
            model_name='formsdata',
            name='unit_9',
            field=models.CharField(default='', max_length=255, verbose_name='作者九所在单位'),
        ),
    ]
