# Generated by Django 5.1.7 on 2025-03-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_formsdata_author_10_formsdata_author_6_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsdata',
            name='other_accept_level',
            field=models.CharField(default='', max_length=255, verbose_name='其他采纳级别'),
        ),
        migrations.AddField(
            model_name='formsdata',
            name='other_instruction_level',
            field=models.CharField(default='', max_length=255, verbose_name='其他批示级别'),
        ),
    ]
